### PR TITLE
add possibility to add points to all the teams

### PR DESCRIPTION
**Pull request by dadokkio**
#193 possible workaround that permit admin to increase all the users points simultaneously.

### CODE REVIEW

**Comment by dadokkio** [comment]
#196  added original_value field to permit correct game reset

**Comment by jeffg2k** [comment]
Nice - I'm going to try to work on #189 so that I can roll this in without breaking the db for those that sync.

**Comment by dadokkio** [comment]
I can fix the trailing whitespaces but I'm not sure about the method already defined in Flag.py
I tried to follow the code that you used for other fields so not sure if I need to fix it or not.

**Comment by jeffg2k** [comment]
I didn't realize Codacy was visible on here.  It was something I was testing so that I could do code cleanup and perhaps start using CI.  No worries

**Comment by garanews** [comment]
when do you think this pr will be merged?
Thanks

**Pull request merged**
