### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by jeffg2k**
So we've had this branch out here for a while and I've kept it up to date.  It is compatible with both Python 2.7 & Python 3.6.  I'm not aware of any bugs, but I expect that testing has been limited since people rarely deviate from master.  At some point we should bite the bullet and cut over, addressing any issues that come up.  First creating a new branch with the current Python 2.7.x codebase, so that if users run into issues, they can quickly switch branches and be back in business (assuming they have Python 2 installed as well).

### CODE REVIEW

**Comment by moloch--** [comment]
Sounds like a plan to me, you `git tag` the 2.7 branch too.

**Comment by ekstrah** [comment]
Did you stop supporting python3?

**Comment by moloch--** [comment]
@ekstrah - `master` is now the Python 3 branch.

**Comment by ekstrah** [comment]
> @ekstrah - `master` is now the Python 3 branch.

Yeah but seems like there are problems when installing it. I will try to figure it out but when I can't then will create an issue but thanks :D

**Comment by jeffg2k** [comment]
I'm not aware of any install problems, so if you find any, please let us know the issue / resolution. :)

**Pull request merged**
