### PR TITLE
VS Code Dev Container

### PR DESCRIPTION
**Pull request by askew**
To make development easier by having a ready to go development environment.

This PR adds the files needed to set up a [Dev Container][devcontainers] in [Visual Stidio Code][vscode].

It uses the [docker-compose][compose] configuration to set up three containers, one for the __RootTheBox__ app, one for __memcached__, and one for __MySQL__. A custom Dockerfile is used for the development environment that has the MySQL tools installed on it.

Once the containers have started, the `postCreateCommand` runs the RootTheBox setup to create the database.

Once hit [Run to start debugging][debug]. 

~~___NOTE:__ There is one issue that I've not managed to figure out yet. The very first time you set up the containers with a completely clean repo the database setup fails (it can't connect to the database). However once you have a `./files/rootthebox.cfg` it seems to work fine, even if you removed all the containers._~~ Kudos to @anthturner for fixing this.

[vscode]: https://code.visualstudio.com/ "Visual Studio Code - Code editing. Redefined."
[devcontainers]: https://code.visualstudio.com/docs/remote/create-dev-container "Create a development container"
[compose]: https://code.visualstudio.com/docs/remote/create-dev-container#_use-docker-compose "Use Docker Compose"
[debug]: https://code.visualstudio.com/docs/python/debugging "Python debug configurations in Visual Studio Code"

### CODE REVIEW

**Comment by anthturner** [comment]
One thing this breaks is the smooth "restarting application" flow when a source file is modified. The debugger seems to trap whatever is being done by tornado.autoreload, interpreting it as a program exit, so it is not restarted as expected.

Essentially that means that single-file modifications cause the process to exit automatically, and you need to restart the debugger process.

**Comment by jeffg2k** [comment]
Would be nice if we could figure out a fix for the issue described by @anthturner   I haven't had time to mess with it yet, but hope to soon.

**Comment by anthturner** [comment]
There's a PR on the devcontainer branch at @askew's fork which tries to tiptoe around it. That change adds a way to disable the on-by-default autoreload behavior so that individual changes don't constantly restart the application. Not a perfect fix but it does help a lot for devs who compulsively Ctrl+S (like myself)

**Comment by askew** [comment]
This PR now includes the changes from @anthturner that fix the first start issues. Thanks for figuring that one out. The dev experience is now very slick. Clone the repo, open the workspace in VS Code, click re-open in container when prompted, go make a coffee, hit F5 to start debugging.

Also now includes @anthturner's change to optionally disable the `tornado.autoreload`.

**Pull request merged**
